name: Redeemables
version: '${project.version}'
main: dev.sv3ks.redeemables.Redeemables
api-version: 1.21
commands:
  redeem:
    description: Redeem a reward by entering a code
    aliases:
      - code
      - redeemcode
  rareload:
    permission: redeemables.reloadcodes
    description: Reloads Redeemables' config
    aliases:
      - redeemablesreload
      - reloadraconfig
      - redeemablesreload